<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="2.021" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-01-17T10:16:41" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Sale" timestamp="2023-01-17T10:16:41" tests="0" file="/home/nhat-truong/Projects/test-nft/test/Sale.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="2. Update" timestamp="2023-01-17T10:16:41" tests="1" file="/home/nhat-truong/Projects/test-nft/test/Sale.ts" time="1.957" failures="1">
    <testcase name="Sale 2. Update 2.6. Should be fail when update a sale with token is sold" time="0.019" classname="2.6. Should be fail when update a sale with token is sold">
      <failure message="Transaction reverted: function selector was not recognized and there&apos;s no fallback function" type="Error"><![CDATA[Error: Transaction reverted: function selector was not recognized and there's no fallback function
    at CashTestToken.<unrecognized-selector> (contracts/CashTestToken.sol:9)
    at Sale.buy (contracts/Sale.sol:148)
    at <UnrecognizedContract>.<unknown> (0x5fc8d32690cc91d4c39d9d3abcbd16989f875707)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1815:23)
    at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:504:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)]]></failure>
    </testcase>
  </testsuite>
</testsuites>